### ISSUE TITLE
Docker setup incomplete

### ISSUE THREAD

**Issue by nitish6174** [nitish6174/cclib-web#2]
Following needs to be fixed in the docker setup:

- [x] Openbabel installation
- [x] MongoDB instance creation

Prior to the fix, following error was encountered when ```import openbabel``` was called in python code running in docker container:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import openbabel as ob
  File "/usr/local/lib/python3.5/dist-packages/openbabel.py", line 32, in <module>
    _openbabel = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/openbabel.py", line 28, in swig_import_helper
    _mod = imp.load_module('_openbabel', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libopenbabel.so.5: cannot open shared object file: No such file or directory
```

**Comment by nitish6174** [comment]
The openbabel issue was resolved by setting the following environment configuration in docker build:
```
LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib
```
